import { describe, it, expect } from "vitest";
import { signInAs } from "./setup.js";
import { fetchNotifications, fetchUnreadCount, markAsRead, markAllAsRead, createNotification } from "../src/lib/notificationService.js";

describe("notificationService", () => {
  let createdId;
  let tenantAId;

  it("createNotification writes a row (when caller can — RLS may forbid)", async () => {
    const { user } = await signInAs("tenantA");
    tenantAId = user.id;
    const { data, error } = await createNotification({
      userId: tenantAId,
      type: "system",
      title: "Vitest probe",
      body: "Generated by tests/notifications.spec.js",
    });
    // If insert RLS doesn't permit clients to write notifications (most
    // production setups don't), the row is created via triggers in real
    // app flows (chat message, payment recorded, etc.). Tolerate either
    // success or a permission error — the rest of the suite still tests
    // the read path against whatever rows exist.
    if (error) {
      console.warn("[notifications] client-side create disallowed:", error.message);
    } else {
      expect(data?.id).toBeTruthy();
      createdId = data.id;
    }
  });

  it("fetchNotifications returns rows for tenantA", async () => {
    await signInAs("tenantA");
    const { data, error } = await fetchNotifications(tenantAId, { limit: 10 });
    expect(error).toBeFalsy();
    expect(Array.isArray(data)).toBe(true);
  });

  it("fetchUnreadCount returns a non-negative integer", async () => {
    await signInAs("tenantA");
    const { count, error } = await fetchUnreadCount(tenantAId);
    expect(error).toBeFalsy();
    expect(Number.isInteger(count)).toBe(true);
    expect(count).toBeGreaterThanOrEqual(0);
  });

  it("markAsRead + markAllAsRead complete without RLS errors", async () => {
    if (createdId) {
      const { error } = await markAsRead(createdId);
      expect(error).toBeFalsy();
    }
    const { error } = await markAllAsRead(tenantAId);
    expect(error).toBeFalsy();
    const { count } = await fetchUnreadCount(tenantAId);
    expect(count).toBe(0);
  });
});
